### ISSUE TITLE
No documentation, source, community, or organization links

### ISSUE THREAD

**Issue by brion** [Leapcode-Open/landingpage#561]
The landing page at https://www.leapcode.io/ contains no documentation, source, community, or organization links, making this look like a proprietary project that's not community run and is not open source.

Is this correct?

**Comment by tomByrer** [comment]
I'm confused what it is for also; submit PRs though leapcode just to get leapcode-only badges?

**Comment by atulsuresh** [comment]
@brion It's true that most of thing things are not public yet but we truly are a public platform and we can invite you to our codebase on request. we are working on the documentation and links. Most of our frontend code are public as of now. In the next couple of weeks we are releasing a new repository with both backend and frontend code together. We are small team trying to make it happen finding some time from our full time job.
