### ISSUE TITLE
SEO : PageSpeed Optimization

### ISSUE THREAD

**Issue by Dev-Elie** [Leapcode-Open/landingpage#675]
Hi, There's a critical call to improve the landing page.

According to Google developer page insight analysis, [this](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.leapcode.io%2F&tab=desktop) and [this](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.leapcode.io%2F&tab=mobile) needs to be reviewed.

The main fixes required are:

1. Serve images in next-gen formats
2. Reduce unused JavaScript

**Comment by faadil2022** [comment]
The Chrome User Experience Report does not have sufficient real-world speed data for this page.
The Chrome User Experience Report does not have sufficient real-world speed data for this origin.
try t fix this if you can or message me

**Comment by Dev-Elie** [comment]
Great move @faadil2022
